export const DHHMMSS = 'DHHMMSS' // Example: 1:17:30:59 (d:hh:mm:ss)
export const DHHMMSSF = 'DHHMMSSF' // Example: 1:17:30:59.5 (d:hh:mm:ss.S)
export const HHHMMSS = 'HHHMMSS' // Example: 41:30:59 (hhh:mm:ss)
export const HHHMMSSF = 'HHHMMSSF' // Example: 41:30:59.5 (hhh:mm:ss.S)
export const MMMSS = 'MMMSS' // Example: 230:59 (mmm:ss)
export const MMMSSF = 'MMMSSF' // Example: 230:59.5 (mmm:ss:S)
export const SSS = 'SSS' // Example: 92 (sss)
export const SSSF = 'SSSF' // Example: 92.5 (sss:S)
export const L_D = 'L_D' // Example: 2d
export const L_DH = 'L_DH' // Example: 1d 18h
export const L_DHM = 'L_DHM' // Example: 1d 17h 30m
export const L_DHMS = 'L_DHMS' // Example: 1d 17h 30m 59s
export const L_HMS = 'L_HMS' // Example: 41h 30m 59s
export const L_MS = 'L_MS' // Example: 230m 59s
export const L_S = 'L_S' // Example: 92s
export const DEFAULT = HHHMMSS
